#!/usr/bin/env bash

. script/init

script/stop
bundle install -j 4
rails db:create
rails db:migrate
bundler audit --update || exit 1

script/compile-invoker

rails s -p $PROJECT_PORT

# invoker start # --certificate=script/certs/server.crt --private-key=script/certs/server.key
