include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require:
  - activemodel
  - activesupport
domains: []
plugins:
  - solargraph-rails
reporters:
  - rubocop
  - typecheck
max_files: 5000
