# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.3', '>= 7.0.3.1'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

gem 'active_model_serializers', '~> 0.10.0'
gem 'active_queryable'
gem 'auto_preload'
gem 'cancancan'
gem 'devise'
gem 'devise-i18n'
gem 'devise-jwt'
gem 'solipsist', github: 'monade/solipsist'

gem 'monade_rails_generators', github: 'monade/monade_rails_generators'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'jwt'
gem 'rack-cors'

# Performances
gem 'fast_blank', platform: :mri
gem 'multi_json'
gem 'oj'

# Job administration
gem 'sidekiq', '>= 6.4.1'

profiling = (ENV.fetch('RAILS_ENV', 'development') == 'development') || ENV['PROFILER']

gem 'flamegraph', require: profiling
gem 'memory_profiler', require: profiling
gem 'rack-mini-profiler', require: profiling
gem 'stackprof', require: profiling

group :development, :test do
  gem 'database_cleaner'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails', '~> 5.1'

  gem 'factory_bot_rails'
  gem 'rspec_create_model'
  gem 'rspec_match_structure'
  gem 'rswag'
  gem 'rspec_sql_matcher', github: 'monade/rspec_sql_matcher'

  gem 'webmock'
end

group :development do
  gem 'debug'

  gem 'pry-rails'
  gem 'rubocop-rails', require: false
  gem 'standard', '~> 1.9.0'

  gem 'brakeman'
  gem 'bundler-audit'

  gem 'guard', require: false
  gem 'guard-brakeman', require: false
  gem 'guard-bundler', require: false
  gem 'guard-bundler-audit'
  gem 'guard-rspec', require: false
  gem 'rb-readline'

  gem 'rubycritic'
  gem 'rubycritic-small-badge', require: false

  gem 'solargraph'
  gem 'yard'
  gem 'solargraph-rails'
end

group :production do
  gem 'sentry-rails'
  gem 'sentry-ruby'
end
