name: API

on: push

env:
  DATABASE_URL: postgres://postgres@postgres:5432/postgres
  TEST_DATABASE_URL: postgres://postgres@postgres:5432/postgres
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
  REDIS_URL: redis://redis:6379
  POSTGRES_HOST_AUTH_METHOD: trust

jobs:
  test:
    defaults:
      run:
        working-directory: ./api
    runs-on: ubuntu-latest
    container: ruby:3.1
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ""
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: "3.1"
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      # - uses: joshmfrankel/simplecov-check-action@main
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
